/**
 * ============================================================
 * FILE: langgraph/graph.ts
 * PURPOSE: LangGraph pipeline builder for the RAG interview system
 * ============================================================
 *
 * This file defines the full interview RAG pipeline as a LangGraph
 * directed graph. LangGraph is a library from LangChain for building
 * stateful, multi-step agent workflows.
 *
 * HOW LANGGRAPH WORKS:
 *  - You define a shared STATE object (via Annotation.Root).
 *  - Each NODE is an async function that reads some state fields
 *    and returns a Partial<State> to update the state.
 *  - EDGES connect nodes in sequence (or conditionally).
 *  - The graph is COMPILED once and then invoked per-request.
 *
 * PIPELINE EXECUTION ORDER (sequential, one per interview turn):
 *   1. retrieveResume     → Embeds the answer, finds relevant resume chunks
 *   2. retrieveConversation → Finds semantically similar prior Q&A turns
 *   3. fetchRecentMemory  → Gets the last 5 turns chronologically
 *   4. planner            → Decides: follow-up, change topic, or simplify?
 *   5. questionGenerator  → Calls Groq LLM with full RAG context
 *   6. saveMemory         → Embeds and stores the completed Q&A turn
 *   7. END
 *
 * SINGLETON PATTERN:
 *  The compiled graph is expensive to build (registers nodes, validates
 *  edges). It is built once via `buildInterviewGraph()` and cached in
 *  `compiledGraph`. All subsequent calls reuse the same instance.
 *
 * ENVIRONMENT VARIABLES:
 *  - GROQ_API_KEY : Required by questionGenerator
 *  - GROQ_MODEL   : Optional model override
 *  - MONGODB_URI  : Required by retrieve* and saveMemory nodes
 * ============================================================
 */

import { Annotation, StateGraph, END } from '@langchain/langgraph';
import type { ResumeChunk } from '@/models/ResumeChunk';
import type { ConversationMemory } from '@/models/ConversationMemory';
import type { InterviewState } from '@/models/InterviewState';

import { retrieveResume } from '@/langgraph/nodes/retrieveResume';
import { retrieveConversation } from '@/langgraph/nodes/retrieveConversation';
import { fetchRecentMemory } from '@/langgraph/nodes/fetchRecentMemory';
import { planner } from '@/langgraph/nodes/planner';
import { questionGenerator } from '@/langgraph/nodes/questionGenerator';
import { saveMemory } from '@/langgraph/nodes/saveMemory';

// ---------------------------------------------------------------------------
// State Annotation (LangGraph v0.2+ Annotation API)
// ---------------------------------------------------------------------------

/**
 * GraphAnnotation
 * ---------------
 * Defines the SHARED STATE shape for the entire LangGraph pipeline.
 * Each field uses `Annotation<T>` with a reducer function.
 *
 * The reducer `(_a, b) => b` (replace-always) means each node's
 * output completely overwrites the previous value for that field.
 * This is correct for most fields since each node is responsible
 * for computing the latest value.
 *
 * FIELD GROUPS:
 *  Input fields      : Provided by the caller when invoking the graph.
 *  Retrieved context : Filled in by the three retrieval nodes.
 *  Output            : The question generated by questionGenerator.
 */
const GraphAnnotation = Annotation.Root({
  // ── Input fields ──────────────────────────────────────────────────────
  // userId and sessionId scope all DB reads/writes to the correct user/session
  userId: Annotation<string>({ reducer: (_a, b) => b, default: () => '' }),
  sessionId: Annotation<string>({ reducer: (_a, b) => b, default: () => '' }),
  // The question that was just asked in the current turn
  currentQuestion: Annotation<string>({ reducer: (_a, b) => b, default: () => '' }),
  // The candidate's answer to the current question
  latestAnswer: Annotation<string>({ reducer: (_a, b) => b, default: () => '' }),
  // The full interview state (topic, difficulty, counts) — updated by planner
  interviewState: Annotation<InterviewState | null>({
    reducer: (_a, b) => b,
    default: () => null,
  }),

  // ── Retrieved context ─────────────────────────────────────────────────
  // Resume sections most relevant to the current answer (vector search)
  resumeChunks: Annotation<ResumeChunk[]>({ reducer: (_a, b) => b, default: () => [] }),
  // Semantically similar prior Q&A turns (vector search)
  similarConversationTurns: Annotation<ConversationMemory[]>({
    reducer: (_a, b) => b,
    default: () => [],
  }),
  // The last 5 turns chronologically (direct DB fetch, for conversational flow)
  recentTurns: Annotation<ConversationMemory[]>({ reducer: (_a, b) => b, default: () => [] }),

  // ── Output ────────────────────────────────────────────────────────────
  // The question generated by the LLM in questionGenerator
  generatedQuestion: Annotation<string>({ reducer: (_a, b) => b, default: () => '' }),
});

/** The shared state type — derived from the annotation */
export type GraphState = typeof GraphAnnotation.State;

// ---------------------------------------------------------------------------
// Build the LangGraph
// ---------------------------------------------------------------------------

/**
 * Compiled LangGraph for the interview RAG pipeline.
 *
 * Node execution order:
 *   retrieveResume → retrieveConversation → fetchRecentMemory
 *       → planner → questionGenerator → saveMemory → END
 */
function buildInterviewGraph() {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const graph = new StateGraph(GraphAnnotation) as any;

  // ── Register nodes ──────────────────────────────────────────────────────
  graph.addNode('retrieveResume', retrieveResume);
  graph.addNode('retrieveConversation', retrieveConversation);
  graph.addNode('fetchRecentMemory', fetchRecentMemory);
  graph.addNode('planner', planner);
  graph.addNode('questionGenerator', questionGenerator);
  graph.addNode('saveMemory', saveMemory);

  // ── Entry point + sequential pipeline ──────────────────────────────────
  graph.addEdge('__start__', 'retrieveResume');
  graph.addEdge('retrieveResume', 'retrieveConversation');
  graph.addEdge('retrieveConversation', 'fetchRecentMemory');
  graph.addEdge('fetchRecentMemory', 'planner');
  graph.addEdge('planner', 'questionGenerator');
  graph.addEdge('questionGenerator', 'saveMemory');
  graph.addEdge('saveMemory', END);

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return graph.compile() as any;
}

/**
 * getCompiledGraph
 * ----------------
 * Singleton accessor for the compiled LangGraph.
 * Builds the graph once on first call, then returns the
 * cached instance on all subsequent calls.
 *
 * WHY SINGLETON?
 * `buildInterviewGraph()` registers nodes, validates edges, and
 * compiles the graph — this is non-trivial work that should only
 * happen once per process lifecycle, not on every API request.
 */
// Singleton compiled graph
let compiledGraph: ReturnType<typeof buildInterviewGraph> | null = null;

function getCompiledGraph() {
  if (!compiledGraph) {
    compiledGraph = buildInterviewGraph();
  }
  return compiledGraph;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * RunInterviewRAGInput
 * --------------------
 * The input provided to `runInterviewRAG()` for each interview turn.
 * Contains the current context needed for the full RAG pipeline.
 */
export interface RunInterviewRAGInput {
  /** Clerk userId of the authenticated candidate */
  userId: string;
  /** Unique identifier for this interview session */
  sessionId: string;
  /** The interview question that was just asked */
  currentQuestion: string;
  /** The candidate's answer to the current question */
  latestAnswer: string;
  /** The current interview state (null on the very first turn) */
  interviewState: InterviewState | null;
}

/**
 * RunInterviewRAGOutput
 * ----------------------
 * The result returned by `runInterviewRAG()` after the full
 * pipeline executes for one interview turn.
 */
export interface RunInterviewRAGOutput {
  /** The next interview question generated by the LLM */
  generatedQuestion: string;
  /** The updated interview state after planner + saveMemory ran */
  updatedInterviewState: InterviewState | null;
}

/**
 * runInterviewRAG (EXPORTED, ASYNC)
 * ----------------------------------
 * Execute the full RAG interview graph for one question-answer turn.
 *
 * This is the ONLY function the interview API route needs to call.
 * It internally invokes the entire 6-node pipeline and returns
 * just the essential outputs.
 *
 * HOW IT WORKS:
 *  1. Get the singleton compiled graph.
 *  2. Build an initialState object from the input.
 *  3. Invoke the graph — all 6 nodes run sequentially.
 *  4. Extract and return the generated question and updated state.
 *
 * @param input - The current interview turn context.
 * @returns     - The generated follow-up question and updated state.
 */
export async function runInterviewRAG(
  input: RunInterviewRAGInput,
): Promise<RunInterviewRAGOutput> {
  const graph = getCompiledGraph();

  // Build the initial state object from all input fields
  // plus empty defaults for the fields filled in by retrieval nodes
  const initialState: GraphState = {
    userId: input.userId,
    sessionId: input.sessionId,
    currentQuestion: input.currentQuestion,
    latestAnswer: input.latestAnswer,
    interviewState: input.interviewState,
    resumeChunks: [],             // Filled by retrieveResume
    similarConversationTurns: [], // Filled by retrieveConversation
    recentTurns: [],              // Filled by fetchRecentMemory
    generatedQuestion: '',        // Filled by questionGenerator
  };

  // Run all 6 nodes sequentially and get the final state
  const finalState = await graph.invoke(initialState);

  return {
    generatedQuestion: String(finalState.generatedQuestion),
    updatedInterviewState: finalState.interviewState as InterviewState | null,
  };
}
